name: "Terraform main Workflow"
on:
  push:
    branches:
      - main
    paths:
      - terraform/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USER_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  EKS_CLUSTER: vprofile-eks

jobs:
  DEPLOY-INFRA:
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Validating files
        run: terraform validate

      - name: Plan Infrastructure Changes
        id : plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Plan status check
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Apply new Infrastructure
        id: apply
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
      ## parallelism=1 means that create only 1 resource at a time, to remove dependency issues

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get Kube config file # Updates our local kube config file to connect with the eks cluster
        id: getconfig
        if: steps.apply.outcome == 'success'
        run: aws eks update-kubeconfig --region ${{ env.AWS_DEFAULT_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Install Ingress controller 
        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
        run: |
          kubectl get nodes
          kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/cloud/deploy.yaml

        