name: "Terraform main Workflow"
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USER_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  DEPLOY:
    if: contains(github.event.head_commit.modified, 'terraform/')
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Infrastructure Changes
        working-directory: terraform
        run: terraform plan

      # - name: Deploy new Infrastructure
      #   working-directory: terraform
      #   run: terraform apply -auto-approve

